# Generated by Django 4.2.3 on 2023-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=100)),
                ('student_course', models.CharField(max_length=100)),
            ],
        ),
    ]
