# Generated by Django 4.2.3 on 2023-08-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
    ]
